### ISSUE TITLE
Python version / package versions

### ISSUE THREAD

**Issue by bittnerma** [chi0tzp/FALCO#6]
Hi,

Could you provide the specific python and the pytorch versions that everything was tested on? 
I'm running into issues with the `invert.py` script and my best guess at this point is that it's due to differences in pytorch versions. 

Cheers

**Comment by hanweikung** [comment]
I am having the same issue when running `invert.py` and wondering what versions of packages to use.

```bash
user@amd-pc ~/r/FALCO (master)> python invert.py -v --dataset=celebahq
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/home/user/miniconda3/envs/falco/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/repos/FALCO/invert.py", line 7, in <module>
    from models.psp import pSp
  File "/home/user/repos/FALCO/models/psp.py", line 7, in <module>
    from models.encoders import psp_encoders
  File "/home/user/repos/FALCO/models/encoders/psp_encoders.py", line 9, in <module>
    from models.stylegan2.model import EqualLinear
  File "/home/user/repos/FALCO/models/stylegan2/model.py", line 7, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/user/repos/FALCO/models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/user/repos/FALCO/models/stylegan2/op/fused_act.py", line 9, in <module>
    fused = load(
  File "/home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/TH -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/user/miniconda3/envs/falco/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++17 -c /home/user/repos/FALCO/models/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/TH -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/user/miniconda3/envs/falco/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++17 -c /home/user/repos/FALCO/models/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[2/3] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/TH -isystem /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/user/miniconda3/envs/falco/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp -o fused_bias_act.o 
In file included from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/c10/util/Exception.h:4,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/c10/core/Device.h:5,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:11,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/extension.h:5,
                 from /home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp:1:
/home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp: In function ‘at::Tensor fused_bias_act(const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float, float)’:
/home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp:7:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
    7 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                         ^
/home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp:13:5: note: in expansion of macro ‘CHECK_CUDA’
   13 |     CHECK_CUDA(input);
      |     ^~~~~~~~~~
In file included from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/extension.h:5,
                 from /home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp:1:
/home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/c10/util/Exception.h:4,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/c10/core/Device.h:5,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:11,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/extension.h:5,
                 from /home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp:1:
/home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp:7:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
    7 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                         ^
/home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp:14:5: note: in expansion of macro ‘CHECK_CUDA’
   14 |     CHECK_CUDA(bias);
      |     ^~~~~~~~~~
In file included from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/torch/extension.h:5,
                 from /home/user/repos/FALCO/models/stylegan2/op/fused_bias_act.cpp:1:
/home/user/miniconda3/envs/falco/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
ninja: build stopped: subcommand failed.
```

**Comment by hanweikung** [comment]
It appeared that I needed to install the CUDA toolkit (not the cudatoolkit installed via conda) to address the problem. My environment consists of PyTorch 2.1.1, CUDA 12.0, and CUDA Toolkit 12.3.
